---
title: "Data and code for Dziuba et al paper on O pajunii"
author: "Marcin Dziuba & Meghan Duffy"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(tidyverse)
library(here)
library(patchwork)
library(ggpubr)
library(scales)
library(lubridate)

```

## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/MicGdescription.Rmd")

# Load the data
fielddata2016<-readr::read_csv(here("data/2016_dent_timeseries.csv"))
summary(fielddata2016)

# Note: in this data set, the MicG is labeled as "gut".

# Use lubridate in tidyverse to get dates working properly
fielddata2016 <- fielddata2016 %>%
  mutate(Date = dmy(Date))

```

```{r, plot infection time series}
propinfadovertimeplot<-ggplot(fielddata2016,aes(x=Date, y=gut.prev.adu, group=Lake, color=Lake, shape=Lake)) +
  geom_point() + 
  scale_shape_manual(values=c(15,16,17,18)) +
  labs(color="Lake", shape = "Lake") +
  scale_colour_manual(values=c("#800080", "#39568CFF", "#238A8DFF","black")) +
  geom_smooth(span=0.4, se=FALSE) +
  labs(x="Date", y="Proportion of adults infected") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Format x-axis with month names +
  theme_bw() + 
  theme(legend.position = c(0.1, 0.85)) +
  theme(legend.key.size = unit(0.05, 'cm'), legend.title = element_text(size=10), 
        legend.text= element_text(size=8)) 
propinfadovertimeplot

ggsave(here("figures", "propinfadovertimeplot.jpg"), propinfadovertimeplot, units = "in", width = 6, height = 4, dpi = 300)

ggsave(here("figures", "propinfadovertimeplot.eps"), propinfadovertimeplot, units = "in", width = 6, height = 4, dpi = 300)

ggsave(here("figures", "propinfadovertimeplot.tiff"), propinfadovertimeplot, units = "in", width = 6, height = 4, dpi = 300)

```



```{r, basic summary of sampling}
samplesizes <- fielddata2016 %>%
  summarise(meantotal = mean(Total), mediantotal = median(Total), mintotal = min(Total), maxtotal = max(Total)) 

samplesizeplot<-ggplot(fielddata2016,aes(x=Date, y=Total, group=Lake, color=Lake, shape=Lake)) +
  geom_point() + 
  scale_shape_manual(values=c(15,16,17,18)) +
  labs(color="Lake", shape = "Lake") +
  scale_colour_manual(values=c("#800080", "#39568CFF", "#238A8DFF","black")) +
  geom_smooth(span=0.4, se=FALSE) +
  labs(x="Date")+
  labs(y="# individuals examined for infection") + 
  theme_bw()
samplesizeplot

maxinfection <- fielddata2016 %>%
  group_by(Lake) %>%
  summarise(maxprev = max(gut.prev.all), maxadprev = max(gut.prev.adu)) 

ggsave(here("figures", "samplesizeplot.jpg"), samplesizeplot, units = "in", width = 5, height = 4, dpi = 300)
```

